### ISSUE TITLE
Concurrent requests have undefined outcome

### ISSUE THREAD

**Issue by kaste** [Polymer/core-ajax#12]
Since all properties of an `<core-ajax>` are mutable but the responses come in async, we have the following behavior: http://jsbin.com/qemos/1/edit

T.i. as soon as we issue new requests before we have a response from a previous request, maybe just by changing the url, the public properties of the element and the responses get out of sync. This makes it impossible to _just_ wire up a set of say `<a>`-links with one and only one `<core-ajax>`, because the user tends to re-click on another link, if the responses don't come in fast enough. Another example: You can't wire up an `<core-ajax>` with an `<cache>`-element, because the request and its response can't be enclosed just using an element.

One option is to solve this on an even higher level: just like so http://jsbin.com/piquq/2/edit

```
  <polymer-element name="high-level-ajax" extends="core-ajax">
    <script>
      Polymer('high-level-ajax', {
        go: function(){
          if (this.currentXhr) {
            this.currentXhr.abort();
          }
          return this.currentXhr = this.super();
        }
      });
    </script>
  </polymer-element>
```

But this isn't exactly what we want. To reuse a `xhr`, we would just invoke its `open` method again, which we can't right now using inheritance and re-composition.

But I would argue that this should be implemented in the `<core-xhr>` anyway. The name of the element already suggests that it just wraps a `XMLHttpRequest`. Its `request` method would be just a convenient combination of calling `open` and then `send` on it. 

We still had the option to create as many `<core-xhr>` elements as we want and need. Each element would be a safe entry-point for concurrent/parallel requests.

**Comment by mercmobily** [comment]
Since this is Polymer 0.5, is this still even an issue?
