### ISSUE TITLE
core-complete fires when unable to contact the server for any reason

### ISSUE THREAD

**Issue by bearfriend** [Polymer/core-ajax#58]
If a request fails or is aborted for any reason, `core-ajax` does not recognize the error and fires `on-core-complete` instead of `on-core-error`. Is there another way to handle this, or should errors of this type fire `on-core-error`?

Here are some examples of errors:
https://support.google.com/chrome/answer/117805?hl=en

**Comment by garlicnation** [comment]
https://www.polymer-project.org/docs/elements/core-elements.html#core-ajax

core-complete fires with success or failure, core-response fires on success, core-error fires on failure.

Are you saying that core-error isn't firing for failures? If so, please link to an example and I'll investigate.

**Comment by bearfriend** [comment]
Whoops. Sorry, I did mix those up above, but yes, I am saying `core-error` is not firing.

http://jsfiddle.net/rsecwso3/

Notice the request failed, but `core-response` is fired and `core-error` is not.

**Comment by garlicnation** [comment]
Excellent catch!

The error is here:
```javascript
isSuccess: function(xhr) {
      var status = xhr.status || 0;
      return !status || (status >= 200 && status < 300);
    },
```

!0 is true in javascript. I'll look at this again in the morning, should be a 1-line fix.
