### ISSUE TITLE
loading local files is broken on iOS

### ISSUE THREAD

**Issue by sfeast** [Polymer/core-ajax#75]
iOS returns status 0 when loading local files.

**Comment by sfeast** [comment]
Wasn't familiar with core-complete event until now…thinking that's a better way to handle iOS's non-standard status on local file loads since it's always fired, rather than complicate the status checking. i.e. on local file loads watch for the core-complete event & handle accordingly, since it's always fired.

Also fyi to anyone running into trouble & finding this bug, make sure to use an async ajax request for local files on iOS, otherwise the core-* events don't seem propagate properly.

**Comment by victoriaSh** [comment]
I also find this problem with response = 0 for local files. I use:
this.async(function() { ajaxMain.go(); }
core-ajax works at browser and android but doesn't work at ios.
Have you found how to resolve this problem?
