### ISSUE TITLE
[0.8] broken in IE11

### ISSUE THREAD

**Issue by IntranetFactory** [Polymer/core-ajax#78]
the 0.8-preview version uses Promise() - which seems to be not available in IE11

**Comment by IntranetFactory** [comment]
I just saw that it should be "fixed" now - but I think that having to load yet another polyfill (which is even "considered experimental and unstable") to maybe save some lines of code should be reconsidered. Don't understand why Promises had been added here at all.

**Comment by IntranetFactory** [comment]
New version just failing with a different error
![2015-03-24_1810](https://cloud.githubusercontent.com/assets/7462342/6813989/d479fc10-d250-11e4-85e5-eb54f4660b98.png)

**Comment by cdata** [comment]
@IntranetFactory 0.8-preview elements are implicitly experimental and unstable right now, so your patience is appreciated.

I'll look into this, although repro steps would be appreciated. Thanks!

**Comment by IntranetFactory** [comment]
I need to prepare an isolate test case. So main question is - should it work in IE11? Is there a demo page which I can use to verify that it's working? core-ajax/demo/index.html at least doesn't work for me. Should that page show a result?

That's the stack trace I get
![2015-03-24_1904](https://cloud.githubusercontent.com/assets/7462342/6814798/7f52020c-d258-11e4-8284-9999370db9f5.png)

**Comment by cdata** [comment]
@IntranetFactory the demo has not been ported yet. That work is still in progress. Please refer to the tests if you would like to verify that the browser is working for now.

**Comment by IntranetFactory** [comment]
An isolated test works - so I'm sorry, it seems that our code fails

**Comment by cdata** [comment]
@IntranetFactory I have merged in a new demo this morning. Please let me know if it works for you in IE 11.

**Comment by IntranetFactory** [comment]
It works now again, thank you. Still wondering why yet another polyfill was introduced for something which worked well without Promise in the past. Seems strange that core has now a dependency on a PolymerLabs component. So will the polyfill be moved from PolymerLabs to Polymer and become part of 0.8?

**Comment by cdata** [comment]
Thanks for the feedback. Once again, the 0.8-preview elements are currently experimental and unstable. If the promise polyfill is objectionable to you for any reason, it would be helpful to have an issue dedicated to the discussion. Would you mind creating a new one where we can track the conversation?
